FROM python:3
RUN apt-get update

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY app/db.py db.py
COPY app/scrapetools.py scrapetools.py
COPY app/telegramtools.py telegramtools.py
COPY app/vkoutlet.py vkoutlet.py

CMD ["python", "vkoutlet.py"]
